name: CI Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubantu-latest

    steps:
    - name: checkout code
      uses: actions/checkout@v2
      with:
        python-version: '3.9'

    - name: Install dependencies
      run:  |
        python -m pip install --upgrade pip
        pip iinstall pytest streamlit

    - name: Run tests
      run:  |
        pytest _test.py
